Models/ErrorViewModel.cs
namespace App_Tarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Tarefa.cs
namespace App_Tarefas.Models
{
    public class Tarefa
    {
        //Nome da chave primaria deve ser Nome da classe + "Id"
        public int TarefaId { get; set; } //Id é a chave primaria
        public string? Titulo { get; set; }
        public string? Descricao { get; set; }
        public bool Concluida { get; set; }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using App_Tarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace App_Tarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TarefasController.cs
using App_Tarefas.Models;
using Microsoft.AspNetCore.Mvc;

namespace App_Tarefas.Controllers
{
    public class TarefasController : Controller
    {
        //Lista em memoria(grava as informações apenas quando a apliação esta rodando)
        private static List<Tarefa> _tarefas = new List<Tarefa>();
        private static int _proximoId = 1;
        //GET: Tarefas
        public IActionResult Index()
        {
            return View(_tarefas);// Envia a lista de tarefas como parametro para a pagina Index.
        }
        //GET: Tarefas/Criar
        //GET -> Metodo para "pegar" a pagina e exibir
        public IActionResult Create()
        {
            return View();
        }
        //POST: Tarefas/Criar
        [HttpPost] //Específica que esse metodo responde a requisições POST
        [ValidateAntiForgeryToken] //Protege contra ataques 
        public IActionResult Create(Tarefa tarefa)
        {
            if (ModelState.IsValid) //Verifica se os dados enviados são validos
            {
                tarefa.TarefaId = _proximoId++;
                _tarefas.Add(tarefa); //Adiciona a nova tarefa a lista
                return RedirectToAction("Index"); //Redireciona para a ação Index
            }
            return View(tarefa); //Se os dados não forem validos, retorna a mesma view com os dados preenchidos
        }

        public IActionResult Edit(int id)
        {
            //var tarefa = _tarefas[id]; //Trabalhando com lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);

        }

        //POST: Tarefas/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Tarefa tarefaAtualizada)
        {
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);

            tarefa.Titulo = tarefaAtualizada.Titulo;
            tarefa.Descricao = tarefaAtualizada.Descricao;
            tarefa.Concluida = tarefaAtualizada.Concluida;

            return RedirectToAction("Index");

        }
        //GET: Tarefas/Edit/1
        public IActionResult Details(int id)
        {
            //var tarefa = _tarefas[id]; //Trabalhando com lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);


        }
        //GET: Tarefas/Edit/1
        public IActionResult Delete(int id)
        {
            //var tarefa = _tarefas[id]; //Trabalhando com lista
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            return View(tarefa);

        }
        //Post: Tarefas/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteConfirmed(int id)
        {
            var tarefa = _tarefas.FirstOrDefault(t => t.TarefaId == id);
            if (tarefa != null)
            {
                _tarefas.Remove(tarefa); //Remove a tarefa da lista
            }
            return RedirectToAction("Index");


        }
    }
}

Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Pagina Inicial";
}
<div class="container npy-5">
	<div class=" text-center mb-5">
		<h1 class=" diplay-4 fw-bold"><i class="bi bi-list-stars"></i>AppTarefas</h1>
		<p class=" lead text-muted">gerencie suas tarefas diarias de uma forma simples e eficiente</p>
		<a asp-controller="Tarefa" asp-action="Index" class=" btn btn-primary btn-lg mt-3">ver minhas Tarefa </a>
	</div>
	<div class="row text-center">

		<div class="col-12 col-md-4 mb-4">

			<div class="card shadow-sm">
				<div class="card-body">
					<i class="bi bi-plus-circle display-4 text-primary mb-3"></i>
					<h5>Adicionar Tarefa</h5>
					<p class="card-text text-muted">
						Crie novas tarefas rapidamente para não perder nenhuma atividade.
					</p>
				</div>
			</div>
		</div>

		<div class="col-12 col-md-4 mb-4">

			<div class="card shadow-sm">
				<div class="card-body">
					<i class="bi bi-check-circle display-4 text-success mb-3"></i>
					<h5>Marcar com Concluída</h5>
					<p class="card-text text-muted">
						Marque suas tarefas como concluída para manter o foco no que importa.
					</p>
				</div>
			</div>
		</div>

		<div class="col-12 col-md-4 mb-4">

			<div class="card shadow-sm">
				<div class="card-body">
					<i class="bi bi-trash display-4 text-danger mb-3"></i>
					<h5>Excluir Tarefa</h5>
					<p class="card-text text-muted">
						Remova tarefas que não são mais necessárias de forma fácil.
					</p>
				</div>
			</div>
		</div>

	</div>
</div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/appTarefas.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-light navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <i class="bi bi-list-stars"></i>appTarefas</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>


						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Tarefas" asp-action="Index">Lista de Tarefas</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted fixed-bottom">
		<div class="container">
			&copy; 2025 - appTarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefas/Create.cshtml
@model App_Tarefas.Models.Tarefa
@{
	ViewData["Title"] = "Cadastro de tarefas";

}
<h1>Nova Tarefa</h1>
<form asp-action="Create" method="post">
	<div class="form-group">
		<label>Titulo</label>
		<input asp-for="Titulo" class="form-control" />
	</div>
	<div class="form-group">
		<label>Descriçao</label>
		<textarea asp-for="Descricao" class="form-control"></textarea>
	</div>
	<button type="submit" class="btn btn-success">Salvar</button>
	<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary">Voltar</a>
</form>

Views/Tarefas/Delete.cshtml
@model App_Tarefas.Models.Tarefa
@{
	ViewData["Title"] = "Ecluir Tarefa";
}

<h1>Excluir Tarefa</h1>
<p>Tem certeza que deseja excluir a tarefa "<b>@Model.Titulo</b>"?</p>

<form asp-action="Delete" method="post">
	<input type="hidden" asp-for="TarefaId" />
	<button type="submit" class="btn btn-danger">Excluir</button>
	<a asp-action="Index" class="btn btn-secondary">Cancelar</a>
</form>

Views/Tarefas/Details.cshtml
@model App_Tarefas.Models.Tarefa
@{
	ViewData["Title"] = "Detalhes da Tarefa";
}

<h1>Detalhes da Tarefa</h1>

<p><b>ID:</b> @Model.TarefaId</p>
<p><b>Título:</b> @Model.Titulo</p>
<p><b>Descrição:</b> @Model.Descricao</p>
<p><b>Conluída:</b> @(Model.Concluida ? "Sim" : "Não")</p>

<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary mt-3">Voltar</a>

Views/Tarefas/Edit.cshtml
@model App_Tarefas.Models.Tarefa
@{
	ViewData["Title"] = "Cadastro de tarefas";

}
<h1>Nova Tarefa</h1>
<form asp-action="Create" method="post">
	<div class="form-group">
		<label>Titulo</label>
		<input asp-for="Titulo" class="form-control" />
	</div>
	<div class="form-group">
		<label>Descriçao</label>
		<textarea asp-for="Descricao" class="form-control"></textarea>
	</div>
	<button type="submit" class="btn btn-success">Salvar</button>
	<a asp-controller="Tarefas" asp-action="Index" class="btn btn-secondary">Voltar</a>
</form>

Views/Tarefas/Index.cshtml
@model List<App_Tarefas.Models.Tarefa>
@{
	ViewData["Title"] = "Tarefas";

}
<h1 class="display-4 fw-bold">Lista de tarefas</h1>
<a class="btn btn-primary btn-lg" asp-controller="Tarefas" asp-action="Create">Nova Tarefa</a>

<table class="table table-bordered table-striped mt-3">

	<thead>
		<tr>
			<th>ID</th>
			<th>Título</th>
			<th>Concluída</th>
			<th>Ações</th>

		</tr>
	</thead>

	<tbody>
		@foreach (var tarefa in Model)
		{
			<tr>
				<td>@tarefa.TarefaId</td>
				<td>@tarefa.Titulo</td>
				<td>@tarefa.Concluida</td>
				<td>
					<a aps-controller="Tarefas" asp-action="Details" asp-route-id="@tarefa.TarefaId" class="btn btn-info btn-sm me-2">Detalhes</a>

					<a aps-controller="Tarefas" asp-action="Edit" asp-route-id="@tarefa.TarefaId" class="btn btn-warning btn-sm me-2">Editar</a>

					<a aps-controller="Tarefas" asp-action="Delete" asp-route-id="@tarefa.TarefaId" class="btn btn-danger btn-sm me-2">Excluir</a>
				</td>

			</tr>
		}


	</tbody>

</table>